### ISSUE TITLE
Find a way to better visualize the Miami-Dade budget

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/project-ideas#35]
Given all the talk/drama/news about the county cutting libraries because of the budget, simplify the budget: Use CSS/JS/d3.js to make the Miami-Dade County budget something people understand, because this is still kind of a hot mess: http://www.miamidade.gov/budget/fy14-15-proposed-volume1.asp - see http://openbudgetoakland.com/ (Oakland CA) for comparison.

**Comment by HiGregory** [comment]
Assigning this to MG and moving it over to done since code for this project has been provided in 15' by Mauro Perez. Link --> https://github.com/Code-for-Miami/miami-budget
