### ISSUE TITLE
Build a REST API that scrapes Restaurant inspections in Miami-Dade County

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/project-ideas#50]
### “How Might We” statement

How might we build an REST API of local Restaurant Health Inspection data such that developers can build relevant web applications and websites that expose that kind of data?
### Who will benefit (directly and indirectly) from this project?

Directly benefit: Developers! Developers who are learning to code!
Indirectly benefit: Everyone! 
### What sources do you have?
- Raw data from the State of Florida: http://www.myfloridalicense.com/dbpr/sto/file_download/public-records-food-service.html
- Looks like Channel 10 did something but it's not really updated: http://restaurantinspections.local10.com/home/sfl/records/68/U0FSQVNPVEE/5837668

**Comment by leordev** [comment]
Hello guys,

I'm gonna do this project under this repository https://github.com/Code-for-Miami/restaurant-inspections-api which was created by @CristinaSolana 

😄

**Comment by leordev** [comment]
Hey guys, I have made a quick test preview here (it selects the top 10 inspections with most violations which means its the bad ones):

https://restaurant-inspections.herokuapp.com/top10

PS: I did not load the full data, only about 100 records from the first 4 districts...

Now we need to discuss two things:
1) What endpoints (fields and filters) are we going to provide to the public?
2) How we are going to update the database? (I was thinking about a job that reads the Florida State CSVs daily/hourly)

**Comment by leordev** [comment]
Hello guys!

I think the the service has already the pretty necessary basic endpoints that the consumers would require.

There's all the available endpoints on the wiki https://github.com/Code-for-Miami/restaurant-inspections-api/wiki

**Comment by ErnieAtLYD** [comment]
Great job! :D I may add some specific things to the task, but a lot of what
I'll add will be in the form of documentation.

**Comment by ErnieAtLYD** [comment]
As far as how we are going to update the database, I was also thinking a cron job or a heroku scheduler. Have a script read what you have, maybe checking first to see if a record is already in the DB, and add it if's new.

**Comment by jjc12** [comment]
I'm confused on whether "AI - 13 Clean clothes; hair restraints; jewelry; painted/artificial fingernails" is bad or good because clean clothes and hair restraints are good, but jewelry and painted/artifical fingernails is ambiguous.

Another example is "AD - 08 † Food protection, cross-contamination" Is the food protected? How does it get cross-contaminated then? I don't understand.

And another one: "AQ - 21 Wiping cloths; clean and soiled linens; laundry facilities" - clean and soiled linens? How am I supposed to interpret this?

**Comment by leordev** [comment]
I have the same problem here... Unfortunately this is the only source of official docs that we have: 
"January 1, 2013, the Division of Hotels and Restaurants adopted provisions of the 2009 Food and Drug Administration (FDA) Food Code. One of the most important changes is a new three-tiered violation classification system that replaces the “critical” or “non-critical” classification. The new system uses the terms “High Priority,” “Intermediate” and “Basic” which better define violation information for operators and consumers, making the whole process easier to understand. While the numbering system is similar to the old one, each numbered violation contains several detailed citations that may include any or all of the three-tiered priorities. For more information, see our webpage. Risk factors are still denoted below by the cross (†) symbol. The asterisk (*) denotes good retail practices that are considered a primary concern that must be corrected immediately."

Then what I think is 08 can be interpreted that the food was not protected and could be cross-contaminated. As it's the cross symbol in the front it is a High one.

What I interpret on 13 is that the employees did not have clean clothes or they were using jewelry or fingernails etc. As it has no cross or asterisk it should be basic...

I have no idea about 21 but it should be basic too... Maybe @ernieatlyd can you send them an email asking about more explanation about these codes...

**Comment by jjc12** [comment]
@leordev  That's a great intuitive response. I'm going to pull the types of inspections per city and figure it out later. I also suggest @ErnieAtLYD send them an e-mail

**Comment by jjc12** [comment]
@ErnieAtLYD @leordev  Do we have a data set about the dates that legislation and regulations for restaurants were implemented? It can have an effect on the types of violations showing up at date X.

**Comment by leordev** [comment]
@jjc12 I think this has the violations explanations: http://www.myfloridalicense.com/dbpr/documents/foodviolations2009fc.pdf

**Comment by ErnieAtLYD** [comment]
Because code is now in another repo I'm going to close this!
