### ISSUE TITLE
Create a catalog page for ways to visual data for Civic Engagement apps

### ISSUE THREAD

**Issue by HiGregory** [Code-for-Miami/project-ideas#64]
## Problem
It's hard some time knowing what charts or graph are best to use
for civic data related projects.

## Proposed Solution
Create a page with ways and approaches for visualizing data
using real data.

## Who benefits?
Hackers working on projects related to data visualization.

## Suggested Starting Point
Add as a page on the current MG project and find a list of resources to create this list with.

## Issue Areas
- Open Government/Transparency

## What is the current state of your project idea?
-Concept

## Tell us more about the current state of your project idea.
In Process. 

## Do you have any links to news articles, text, mockups, code, or data?
Source of inspiration: https://datavizcatalogue.com/

## Who are you?
Gregory Johnson, Core Team at Code For Miami

**Comment by ErnieAtLYD** [comment]
So, a portal? Or a mega dashboard?

**Comment by HiGregory** [comment]
**Portal for external use.

**Comment by HiGregory** [comment]
Update -- perhaps make the portal focused on a single vertical for Miami.
Ex. Miami's Health District is the 2nd Largest in the US perhaps launching initiative for Open Data around Public Health or Health Care?

**Comment by HiGregory** [comment]
Current graph project and this overlap. Closing this.
