### ISSUE TITLE
Visualizing School Performance Data for Miami-Dade Public Schools

### ISSUE THREAD

**Issue by HiGregory** [Code-for-Miami/project-ideas#76]
## Idea

Miami-Dade County Public Schools keeps rather up to date spreadsheets with school
performance and graduation data. Why not take this data and create a dashboard or visual
platform to provide insight into the data and our city?

## Project Concept

Build visualizations tools using existing Miami-Dade Public School performance data
to assist educators, parents, and researchers. 

## Who will benefit from your project? 

Education Professionals -- professionals who're core concern is viewing and understanding this data.
Parents -- parent's considering what schools are the best for their child or family member.
Researchers -- people looking for quick references and insights into the MD County school performance.

### User Story
A user is curious about the public school system here in Miami. Typically they do a Google search
or seek a school report (what schools market) to understand their school performance. Now they can use this tool to get visualizations on performance, graduation rates and other things.

###  Quote
"It would be cool if you could create visuals that could help me see by districts what schools
would be good for our organization to start campaigning too for our Dual Enrollment program." -FIU faculty

## Issue Area
- Education

## Concept
- I have an idea or **concept** of a solution but have not yet prototyped or tested it

## Tell us more about the current state of your project idea.
Cleaned and ETL data points. Now looking for best tools to use to prototype the idea.

### Do you have any links to news articles, text, mockups, code, or data?

Work in progress.

## Tell us about yourself. 
Gregory - Civic Hacker. This project was requested.

**Comment by jmjames5x** [comment]
Hi Gregory!,

I'm new to Miami - I relocated from Washington, D.C. about a month ago.  I have a business background and am transitioning into UX/product design with Ironhack's UX/UI Bootcamp.  I haven't yet been to a Code for Miami meetup, but found this project really interesting.  

I can definitely help with prototyping and testing.  I'll reach out to you directly on social media.

Take care,
Jason

**Comment by HiGregory** [comment]
Wrapping this project up. Visualizations have been made using the data. Updated the requirements. Depending on demand may create website or add these visuals to overall MiamiGraph project.
