### ISSUE TITLE
Brainstorm and research ways to maintain and host Miami Graph for at least a 1 year

### ISSUE THREAD

**Issue by HiGregory** [Code-for-Miami/project-ideas#79]
## Idea

Hosting and maintaining projects takes money. Consider the best hosting options and funding solutions for maintaining this projects. Also create a page dedicated to this and plans for these main items.

- Domain Renewal [$10.69 via Namecheap]
- Hosting Fees [Heroku]
- SSL Certificate [ use CFM]
- Medium Blog Fee [ use CFM]
- Funding Page [ Chris is working on]

**Comment by CyberStrike** [comment]
1. Domain Renewal

    What's the cost of the domain, maybe we can transfer it to open.miami

2. Hosting Fees

   Hosting on heroku is free, if we need an always on dyno we can cover that too.

3. SSL Certificates
   
    SSL Certificates are free.

4. Medium Blog Fee

   Code For Miami has medium publication account, what's the premium feature Miami Graph would need?

5. Create a page dedicated to this and plans for these main items

    Creating guides on projects is one of todos I need find time to make a todo list on. My new motto is "Document all the things!"

**Comment by HiGregory** [comment]
**Domain Renewal** - It's on Namecheap so $10.69 a year last time I checked.
**Hosting Fees** - Heroku it is.
**SSL Certificates** - Do we have a wildcard? At the moment just SSL works.
**Medium Blog Fee -** I meant custom domain, but now you mentioned it hosting under CFM
would be a good generally because we already have a following.

Got it will be update the original issue.

**Comment by CyberStrike** [comment]
In regards to the SSL, if it's hosted on heroku we can generate a letsencrypt certificate.

**Comment by HiGregory** [comment]
That seems to be all we need to sort out for a MVP. Cool, because I created an Excel sheet to track costs and currently the biggest cost is domain renewal (we already own MG for a year). I'm closing this.
